### ISSUE TITLE
[Bug] MetashiftManager loads wrong images

### ISSUE THREAD

**Issue by yeongjoonJu** [mertyg/debug-mistakes-cce#3]
First of all, thank you for your work.

I am re-implementing your codes for spurious detection experiments.

By the way, I found that the wrong evaluation images are used.

**Load image list**
~~~python
from dataset import MetashiftManager

dataset_name = "bear-bird-cat-dog-elephant:dog(snow)"
manager = MetashiftManager()
classes, train_domain = dataset_name.split(":")
classes = classes.split("-")
num_classes = len(classes)
shift_class = train_domain.split("(")[0]
spurious_concept = train_domain.split("(")[1][:-1].lower()
print(f"Shift Class: {shift_class}, Spurious Concept: {spurious_concept}")
~~~
Result:
~~~
Shift Class: dog, Spurious Concept: snow
~~~
**Get image list for all classes**
~~~python
class_images = manager.get_class_ims(classes)
len(class_images["dog"])
~~~
Result:
~~~
2580
~~~
**Check images in "dog" class**
~~~python
from PIL import Image
Image.open(class_images["dog"][2077])
~~~
![image](https://user-images.githubusercontent.com/30193942/203493977-df213b2f-2492-46e8-bdd4-c2025e973086.png)

~~~python
from PIL import Image
Image.open(class_images["dog"][1616])
~~~
![image](https://user-images.githubusercontent.com/30193942/203494234-5d108cb0-2ffb-4ba0-a127-4af273f525c9.png)

For classification, there is no "dog" in an image cropped from this image.

Many images in class "dog" are unrelated to class "dog".

Please let me know the reason.

Is your experiment wrong?

I found that the wrong images contain hotdogs...

**Comment by mertyg** [comment]
Hi @yeongjoonJu , 
Thanks for your interest! 

We also observed a couple similar images, Visual Genome annotations (Metashift is derived from VG) can be just a bit noisy. 
In some cases the object/context (e.g. dog) can be hard to see (see the second image, woman on the right, the dog whose head can be seen from the bag :D ) 

However, these images should be the minority, GQA/VG annotations are also mostly reliable and used in many places.  And I don't think it can have an important effect on the CCE score (e.g. some images having dogs that are hard to see should not increase the score of `snow` in any case). The noise would probably have a minor effect on the overall results. 

Let me know if you have any other qs!

**Comment by yeongjoonJu** [comment]
Thank you! I understood.

I have another question for my research.

I am conducting an experiment detecting spurious features without any concept dataset.
I got a result that the white attribution is short.
I think the snow concept is very related to white attribution.

May I interpret that the explanation leads get snow concept because there is no white concept in the concept dataset?
This question is a personal thing so you can close this issue without any answer.

Thank you so much!

**Comment by mertyg** [comment]
That's a great question! 

I would interpret the results the same way. In fact, if you look at the Table 4 in the Appendix of the [CCE paper](https://arxiv.org/pdf/2106.12723.pdf), we have a very similar experiment. If a concept is not in the dataset yet should appear in the explanation, we usually get concepts that are relevant to that as potential explanations. (To me, having a chance to intuit / have a pointer to start is one of the nicer things about concept-based explanations.)

We could expect this behavior, as the `white` CAV has a high (cosine/euclidean) similarity to the `snow` CAV in the embedding space due to visual similarity. Hence, we can speculate that CCE is trying to compensate via pushing in the direction of `snow`, if `white` does not exist. This is mostly due to the linearity assumption made with CAVs. 

I think it'd be interesting to think about non-linear ways to represent concepts!

**Comment by yeongjoonJu** [comment]
Thank you very much for your fast and detailed answer.

I did not feel bored while reading your paper.
I will look forward to your subsequent related work.
